CREATE TABLE IF NOT EXISTS Item (
    ItemID  INT PRIMARY KEY AUTO_INCREMENT UNIQUE,
    Name    VARCHAR(50) NOT NULL,
    Price   INT NOT NULL
);

CREATE TABLE IF NOT EXISTS Weapon (
    ItemID      INT PRIMARY KEY,
    AttackPower INT NOT NULL,

    FOREIGN KEY (ItemID) REFERENCES Item(ItemID)
);

CREATE TABLE IF NOT EXISTS Armor (
    ItemID  INT PRIMARY KEY,
    Defense INT NOT NULL,

    FOREIGN KEY (ItemID) REFERENCES Item(ItemID)
);

CREATE TABLE IF NOT EXISTS Potion (
    ItemID  INT PRIMARY KEY,
    Healing INT NOT NULL,

    FOREIGN KEY (ItemID) REFERENCES Item(ItemID)
);

CREATE TABLE IF NOT EXISTS Artefact (
    ItemID  INT PRIMARY KEY,
    Effect  VARCHAR(50) NOT NULL,

    FOREIGN KEY (ItemID) REFERENCES Item(ItemID)
);
