CREATE TABLE IF NOT EXISTS Monster (
    MonsterID INT AUTO_INCREMENT PRIMARY KEY,
    MonsterName VARCHAR(100) NOT NULL,
    LifePoints INT DEFAULT 100,
    Attack INT DEFAULT 10,
    Defense INT DEFAULT 10
);

