CREATE TABLE IF NOT EXISTS Spell (
    SpellID     INT PRIMARY KEY,
    SpellName   VARCHAR(25) NOT NULL,
    ManaCost    INT NOT NULL DEFAULT 0,
    LoadingTime INT NOT NULL DEFAULT 0,
    AttackPower INT NOT NULL DEFAULT 0
);